### ISSUE TITLE
An error was reported:    HG002_GRCh37_difficult_medical_gene_SV_benchmark_v0.01.vcf            ^ Syntax error: invalid syntax

### ISSUE THREAD

**Issue by smallfire0128** [luojunwei/BreakNet#5]
Hello why am I typing this training command
"python breaknet.py data_mode HG002_PB_70x_RG_HP10XtrioRTG.bam output_data_train 32 HG002_GRCh37_difficult_medical_gene_SV_benchmark_ v0.01.vcf"
An error was reported
"Backtracking (most recent call):
  File "breaknet.py", line 16, in <module>
    bamfilepath, outputpath, max_worker, includecontig = sys.argv[2], sys.argv[3], int(sys.argv[4]), [str(contig) for contig in eval(sys.argv[5])] .
  File "<string>", line 1
    HG002_GRCh37_difficult_medical_gene_SV_benchmark_v0.01.vcf
                                                         ^
Syntax error: invalid syntax
"

**Comment by micahvista** [comment]
Please check this commit https://github.com/luojunwei/BreakNet/tree/af7d77d85cbb758928268851323fa07eb7efc1de. Please make sure the provided VCF has the SVTYPE tag.

**Comment by smallfire0128** [comment]
Traceback (most recent call last):
  File "breaknet.py", line 18, in <module>
    bamfilepath, outputpath, max_worker, includecontig = sys.argv[2], sys.argv[3], int(sys.argv[4]), []
ValueError: invalid literal for int() with base 10: 'HG002_SVs_Tier1_v0.6.vcf'
I re-swapped a copy of the vcf data, which has svtype tags in it, but the above bug still occurs when generating the training data.
The command I entered is: python breaknet.py data_mode 1.bam output_folder HG002_SVs_Tier1_v0.6.vcf

**Comment by micahvista** [comment]
Please check this commit https://github.com/luojunwei/BreakNet/tree/af7d77d85cbb758928268851323fa07eb7efc1de, data labeling and model training are not supported by the latest version.

**Comment by micahvista** [comment]
Please check this version for better multithreading support https://github.com/micahvista/BreakNet/tree/main.
